#原始配置
server:
  port: 8020
spring:
  application:
    name: cloud-stream
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: bilibili
  cloud:
    stream:
      bindings:
        danmu:
          destination: danmu
          group: danmuQueue
          producer:
            requiredGroups: danmuQueue
        gift:
          destination: gift
          group: giftQueue
          producer:
            requiredGroups: giftQueue
        guardBuy:
          destination: guardBuy
          group: guardBuyQueue
          producer:
            requiredGroups: guardBuyQueue
        guardRenew:
          destination: guardRenew
          group: guardRenewQueue
          producer:
            requiredGroups: guardRenewQueue
        superChat:
          destination: superChat
          group: superChatQueue
          producer:
            requiredGroups: superChatQueue
        fans:
          destination: fans
          group: fansQueue
          producer:
            requiredGroups: fansQueue
        guard:
          destination: guard
          group: guardQueue
          producer:
            requiredGroups: guardQueue
      rabbit:
        bindings:
          danmu:
            producer:
              #              bindQueue: false
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: danmu
              routingKey: danmu
          gift:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: gift
              routingKey: gift
          guardBuy:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guardBuy
              routingKey: guardBuy
          guardRenew:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guardRenew
              routingKey: guardRenew
          superChat:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: superChat
              routingKey: superChat
          fans:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: fans
              routingKey: fans
          guard:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guard
              routingKey: guard

# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://124.221.36.8:32761/eureka/
    rest-template-timeout:
      connect-timeout: 30000
      connect-request-timeout: 30000
      socket-timeout: 30000
  instance:
    instance-id: cloud-stream
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health

---
#原始配置
server:
  port: 8020
spring:
  application:
    name: cloud-stream
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rabbitmq-0.rabbitmq-service.default.svc.cluster.local
    port: 5672
    username: admin
    password: admin
    virtual-host: bilibili
  cloud:
    stream:
      bindings:
        danmu:
          destination: danmu
          group: danmuQueue
          producer:
            requiredGroups: danmuQueue
        gift:
          destination: gift
          group: giftQueue
          producer:
            requiredGroups: giftQueue
        guardBuy:
          destination: guardBuy
          group: guardBuyQueue
          producer:
            requiredGroups: guardBuyQueue
        guardRenew:
          destination: guardRenew
          group: guardRenewQueue
          producer:
            requiredGroups: guardRenewQueue
        superChat:
          destination: superChat
          group: superChatQueue
          producer:
            requiredGroups: superChatQueue
        fans:
          destination: fans
          group: fansQueue
          producer:
            requiredGroups: fansQueue
        guard:
          destination: guard
          group: guardQueue
          producer:
            requiredGroups: guardQueue
      rabbit:
        bindings:
          danmu:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: danmu
              routingKey: danmu
          gift:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: gift
              routingKey: gift
          guardBuy:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guardBuy
              routingKey: guardBuy
          guardRenew:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guardRenew
              routingKey: guardRenew
          superChat:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: superChat
              routingKey: superChat
          fans:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: fans
              routingKey: fans
          guard:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: guard
              routingKey: guard

# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_INSTANCE_LIST}
    rest-template-timeout:
      connect-timeout: 30000
      connect-request-timeout: 30000
      socket-timeout: 30000
  instance:
    prefer-ip-address: false
    hostname: ${STREAM_INSTANCE_HOST_NAME}

management:
  endpoints:
    web:
      exposure:
        include: info,health