server:
  port: 8060
spring:
  application:
    name: cloud-service
  config:
    activate:
      on-profile: dev
# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    rest-template-timeout:
      connect-timeout: 30000
      connect-request-timeout: 30000
      socket-timeout: 30000
  instance:
    instance-id: cloud-service
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health

---
server:
  port: 8066
spring:
  application:
    name: cloud-service
  config:
    activate:
      on-profile: prod
# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    rest-template-timeout:
      connect-timeout: 30000
      connect-request-timeout: 30000
      socket-timeout: 30000
  instance:
    instance-id: cloud-service
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
