#原始配置
server:
  port: 8020
spring:
  application:
    name: cloud-stream
    config:
      activate:
        on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: bilibili
  cloud:
    stream:
      bindings:
        fans:
          destination: fans
          group: fansQueue
          producer:
            requiredGroups: fansQueue
      rabbit:
        bindings:
          fans:
            producer:
              exchangeType: direct
              queueNameGroupOnly: true
              bindingRoutingKey: fans
              routingKey: fans

# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://124.221.36.8:32761/eureka/
    rest-template-timeout:
      connect-timeout: 30000
      connect-request-timeout: 30000
      socket-timeout: 30000
  instance:
    instance-id: cloud-stream
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health