server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  config:
    activate:
      on-profile: dev
  cloud:
    #配置路由
    gateway:
      #      #这里可以配置多个路由
      #      routes:
      #        - id: test #路由的id
      ##          uri: http://localhost:8060 #匹配后提供服务的路由地址
      #          uri: lb://cloud-service #匹配后提供服务的路由地址
      #          predicates:
      #            - Path=/** #断言 路径相匹配的进行路由
      discovery:
        locator:
          enabled: true #自动配置
          lower-case-service-id: true #小写
# Eureka server configuration
eureka:
  client:
    #    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: info,health

---
